@startuml Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(client, "Клиент банка")
Person(backEmployee, "Сотрудник бэк-офиса")
Person(callerEmployee, "Сотрудник кол-центра")
Person(externalPartnerEmployee, "Сотрудник партнёрского кол-центра")

Container(website, "Сайт")
Container(internetBank, "Интернет-банк")
Container(absSystem, "АБС")

System_Boundary(depositSystem, "Система для работы с депозитами"){
    Container(depositServiceFrontend, "Фронтенд для сотрудников")
    Container(depositService, "Сервис для работы с депозитами", ".NET")
    ContainerDb(depositServiceDb, "База данных", "PostgreSQL")
    ContainerDb(depositCache, "Кэш", "Redis")
}

Container(smsGateway, "СМС-шлюз телеком-оператора")
Container(fileArchive, "Файловое хранилище")
Container(messageBroker, "Система обмена сообщениями", "Kafka")

Container_Ext(telecomOperator, "Телеком-оператор")

Rel(client, internetBank, "Использует")
Rel(client, website, "Использует")

Rel(backEmployee, depositServiceFrontend, "Использует")
Rel(backEmployee, absSystem, "Использует")
Rel(callerEmployee, depositServiceFrontend, "Использует")

Rel(internetBank, depositService, "Взаимодействует с")
Rel(website, depositService, "Взаимодействует с")

Rel(depositService, smsGateway, "Передает данные в")
Rel(depositService, depositServiceDb, "Использует")
Rel(depositService, depositCache, "Использует")
Rel(depositServiceFrontend, depositService, "Использует")

Rel_R(smsGateway, telecomOperator, "Передает данные в")
Rel(telecomOperator, client, "Взаимодействует с")

Rel_R(depositService, fileArchive, "Сохраняет данные в")
Rel(externalPartnerEmployee, fileArchive, "Использует")

Rel(absSystem, messageBroker, "Взаимодействует с")
Rel(depositService, messageBroker, "Взаимодействует с")

LAYOUT_TOP_DOWN()

@enduml

