@startuml Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(client, "Клиент банка")
Person(backEmployee, "Сотрудник бэк-офиса")
Person(callerEmployee, "Сотрудник кол-центра")
Person(externalPartnerEmployee, "Сотрудник партнёрского кол-центра")

Container(website, "Сайт")

System_Boundary(internetBankSystem, "Интернет-банк"){
    Container(internetBankFrontend, "Фронтэнд")
    Container(internetBank, "Бэкенд", "ASP.NET MVC 4.5")
    ContainerDb(internetBankDb, "База данных", "MS SQL")
}

System_Boundary(absSystem, "АБС"){
    Container(abs, "Клиент", "Deplhi")
    ContainerDb(absDb, "База данных", "Oracle")
}

System_Boundary(depositSystem, "Система для работы с депозитами"){
    Container(depositServiceFrontend, "Фронтенд для сотрудников")
    Container(depositService, "Сервис для работы с депозитами", ".NET/Java/PHP")
    ContainerDb(depositServiceDb, "База данных", "Oracle/MSSQL")
}

Container(smsGateway, "СМС-шлюз телеком-оператора")
Container(fileArchive, "Файловое хранилище")

Container_Ext(telecomOperator, "Телеком-оператор")

Rel(client, internetBankFrontend, "Использует")
Rel(client, website, "Использует")

Rel(backEmployee, depositServiceFrontend, "Использует")
Rel(backEmployee, abs, "Использует")
Rel(callerEmployee, depositServiceFrontend, "Использует")

Rel(internetBank, depositService, "Взаимодействует с")
Rel(website, depositService, "Взаимодействует с")

Rel_R(depositService, smsGateway, "Передает данные в")
Rel(depositService, absDb, "Взаимодействует с")
Rel(depositService, depositServiceDb, "Использует")
Rel(depositServiceFrontend, depositService, "Использует")

Rel_R(smsGateway, telecomOperator, "Передает данные в")
Rel_R(telecomOperator, client, "Взаимодействует с")

Rel(internetBankFrontend, internetBank, "Использует")
Rel(internetBank, internetBankDb, "Использует")

Rel(abs, absDb, "Использует")
Rel_D(depositService, fileArchive, "Сохраняет данные в")
Rel_L(externalPartnerEmployee, fileArchive, "Использует")

LAYOUT_TOP_DOWN()

@enduml

