@startuml Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(client, "Клиент банка")
Person(backEmployee, "Сотрудник бэк-офиса")

Container(website, "Сайт")
Container(internetBank, "Интернет-банк")

System_Boundary(absSystem, "АБС"){
    Container(abs, "Клиент", "Deplhi")
    Container(absMQIntegration, "Интеграция с брокером сообщений", ".NET")
    ContainerDb(absDb, "База данных", "Oracle")
}

System_Boundary(creditSystem, "Система для работы с кредитами"){
    Container(creditService, "Сервис для работы с кредитами", ".NET")
    ContainerDb(creditServiceDb, "База данных", "PostgreSQL")
    ContainerDb(creditCache, "Кэш данных", "Redis")
}

Container(scoringSystem, "Система кредитного скоринга")
Container(smsGateway, "СМС-шлюз телеком-оператора")
Container(messageBroker, "Система обмена сообщениями", "Kafka")

Container_Ext(telecomOperator, "Телеком-оператор")
Container_Ext(creditBureau, "Бюро кредитных историй")

Rel(client, internetBank, "Использует")
Rel(client, website, "Использует")

Rel(backEmployee, abs, "Использует")
Rel(internetBank, creditService, "Взаимодействует с")
Rel(website, creditService, "Взаимодействует с")

Rel_R(creditService, smsGateway, "Передает данные в")
Rel(creditService, creditServiceDb, "Использует")
Rel(creditService, creditCache, "Использует")

Rel_R(smsGateway, telecomOperator, "Передает данные в")
Rel_R(telecomOperator, client, "Взаимодействует с")

Rel(abs, absDb, "Использует")
Rel(creditService, scoringSystem, "Использует")
Rel(creditService, creditBureau, "Использует")

Rel(absMQIntegration, messageBroker, "Взаимодействует с")
Rel(absMQIntegration, absDb, "Использует")
Rel(creditService, messageBroker, "Взаимодействует с")

LAYOUT_TOP_DOWN()

@enduml

